apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: synergychat-crawler
  ports:
  - name: crawler-service
    protocol: TCP
    port: 80
    targetPort: 8001
---

